; generated by Slic3r 1.2.9 on 2016-02-03 at 11:21:38

; external perimeters extrusion width = 0.20mm
; perimeters extrusion width = 0.21mm
; infill extrusion width = 0.21mm
; solid infill extrusion width = 0.21mm
; top infill extrusion width = 0.21mm

G28 ; home all axes
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G1 E-1.00000 F240.00000
G1 Z0.200 F480.000
G92 E0
G1 X1 Y-4 F480.000
G1 E1.00000 F240.00000
G1 X1 Y4 E1.02271 F120.000
G1 X5 Y4 E1.03 F120.000
G1 X5 Y-4 E1.05 F120.000
G92 E0
 
; resolution = 0
; retract_before_travel = 1,1
; retract_layer_change = 1,1
; retract_length = 1,1
; retract_length_toolchange = 1,1
; retract_lift = 0,0
; retract_restart_extra = 0,0
; retract_restart_extra_toolchange = 0,0
; retract_speed = 4,4
; skirt_distance = 6
; skirt_height = 0
; skirts = 0
; slowdown_below_layer_time = 30
; spiral_vase = 0
; standby_temperature_delta = -5
; start_gcode = G28 ; home all axes
; temperature = 0,0
; threads = 2
; toolchange_gcode = 
; travel_speed = 8
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; vibration_limit = 0
; wipe = 0,0
; z_offset = 0
; dont_support_bridges = 1
; extrusion_width = 0
; first_layer_height = 0.2
; infill_only_where_needed = 0
; interface_shells = 0
; layer_height = 0.2
; raft_layers = 0
; seam_position = aligned
; support_material = 0
; support_material_angle = 0
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_spacing = 0
; support_material_interface_speed = 4
; support_material_pattern = pillars
; support_material_spacing = 2.5
; support_material_speed = 4
; support_material_threshold = 0
; xy_size_compensation = 0
; bottom_solid_layers = 0
; bridge_flow_ratio = 1
; bridge_speed = 4
; external_fill_pattern = rectilinear
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 4
; external_perimeters_first = 0
; extra_perimeters = 1
; fill_angle = 45
; fill_density = 99%
; fill_pattern = honeycomb
; gap_fill_speed = 4
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_overlap = 15%
; infill_speed = 4
; overhangs = 1
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_speed = 4
; perimeters = 1
; small_perimeter_speed = 4
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 4
; thin_walls = 1
; top_infill_extrusion_width = 0
; top_solid_infill_speed = 4
; top_solid_layers = 0


