# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 18:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='editsHtml',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 4, 27, 18, 21, 38, 810345))),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 4, 27, 18, 21, 38, 809453))),
                ('edits', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.date(2016, 4, 27))),
            ],
        ),
    ]
