# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editshtml',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 8, 46, 3, 206073)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 8, 46, 3, 203299)),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.DateField(default=datetime.date(2016, 4, 28)),
        ),
    ]
