# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0004_auto_20160512_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editshtml',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 17, 35, 39, 230950)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 17, 35, 39, 230350)),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.DateField(default=datetime.date(2016, 5, 16)),
        ),
    ]
