# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 22:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0008_auto_20160517_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editshtml',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 22, 25, 53, 380149)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 22, 25, 53, 379583)),
        ),
    ]
