# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0010_auto_20160517_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editshtml',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 8, 3, 19, 637930)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 8, 3, 19, 637375)),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='date',
            field=models.DateField(default=datetime.date(2016, 5, 18)),
        ),
    ]
