# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0013_auto_20160518_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editshtml',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 10, 1, 40, 515324)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 10, 1, 40, 514082)),
        ),
    ]
