# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0014_auto_20160518_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editshtml',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 10, 47, 31, 745317)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 10, 47, 31, 744761)),
        ),
    ]
