# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='foto',
        ),
        migrations.AlterField(
            model_name='file',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 8, 46, 3, 196923)),
        ),
        migrations.AlterField(
            model_name='file',
            name='f',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 28, 8, 46, 3, 190579)),
        ),
    ]
