# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 19:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160428_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 30, 19, 38, 20, 934836)),
        ),
        migrations.AlterField(
            model_name='file',
            name='f',
            field=models.FileField(blank=True, null=True, upload_to='media/files/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 30, 19, 38, 20, 931341)),
        ),
    ]
