# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20160512_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='url',
            field=models.URLField(default='http://www.google.com'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 17, 35, 39, 219150)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 16, 17, 35, 39, 216037)),
        ),
    ]
