# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 20:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20160517_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 20, 27, 16, 930187)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 20, 27, 16, 928187)),
        ),
        migrations.AlterField(
            model_name='libraries',
            name='image',
            field=models.TextField(),
        ),
    ]
