# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20160517_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 22, 31, 53, 82184)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 17, 22, 31, 53, 79883)),
        ),
    ]
