# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 08:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20160517_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 8, 3, 19, 629962)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 8, 3, 19, 627953)),
        ),
        migrations.AlterField(
            model_name='libraries',
            name='image',
            field=models.ImageField(upload_to='librariesimage/'),
        ),
    ]
