# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20160518_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.FileField(blank=True, null=True, upload_to='media/libraries/')),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 9, 58, 54, 459503)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 9, 58, 54, 457251)),
        ),
        migrations.AlterField(
            model_name='libraries',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.LibraryImage'),
        ),
    ]
