# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20160518_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Libraries'),
        ),
        migrations.AlterField(
            model_name='file',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 10, 47, 31, 736311)),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 10, 47, 31, 734189)),
        ),
        migrations.AlterField(
            model_name='libraries',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.fotos'),
        ),
        migrations.DeleteModel(
            name='LibraryImage',
        ),
    ]
