# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extuser',
            name='date_of_birth',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date birthday'),
        ),
    ]
